### ISSUE TITLE
Teach guessComponentUpdateDetails about aggregated issues

### ISSUE THREAD

**Issue by rimrul** [git-for-windows/gfw-helper-github-app#11]
The Title `3 new Items` in https://github.com/git-for-windows/git/issues/4164 does not mean the new Version is `3`.

**Comment by dscho** [comment]
I guess we can even special-case this to the package "bash".

@rimrul if you want to work on this, please feel free to do so, I nerd-sniped myself into that PCRE2 update business too much and fell behind on other things I need to do.

I suspect that we will need to port [this patchlevel logic](https://github.com/git-for-windows/build-extra/blob/e54213ed01ae01784a456db2a8d1b072d3f77263/please.sh#L3068-L3075) to [this directory](https://github.com/git-for-windows/git-for-windows-automation/tree/main/update-scripts) so that [`open-pr.yml`](https://github.com/git-for-windows/git-for-windows-automation/blob/main/.github/workflows/open-pr.yml) can pick it up.

**Comment by rimrul** [comment]
Yes, I've started work on this and opened the corresponding https://github.com/git-for-windows/git-for-windows-automation/issues/1

**Comment by dscho** [comment]
@rimrul out of curiosity: is [`test-pr-comment-delivery.js`](https://github.com/git-for-windows/gfw-helper-github-app/blob/main/test-pr-comment-delivery.js) useful to you?

**Comment by rimrul** [comment]
Unfortunately, no. 

https://github.com/settings/apps/gitforwindowshelper/advanced just gives me a 404.

**Comment by dscho** [comment]
> https://github.com/settings/apps/gitforwindowshelper/advanced just gives me a 404.

Sorry about that :-( I had a quick look and did not find a way to give you permission. I will keep looking and ping you once I know more.

**Comment by dscho** [comment]
Ah, it was still owned by me, personally. I transferred ownership to `git-for-windows` and added you as an app manager. @rimrul  could you try again?

**Comment by rimrul** [comment]
I think it works, but the url changed to https://github.com/organizations/git-for-windows/settings/apps/gitforwindowshelper/advanced

**Comment by dscho** [comment]
> I think it works, but the url changed to https://github.com/organizations/git-for-windows/settings/apps/gitforwindowshelper/advanced

Good point. Since you're in the space, would you mind opening a PR to change the instances where a now-obsolete link is mentioned?
